### ISSUE TITLE
Incorrect release tar.gz path for umbrella project

### ISSUE THREAD

**Issue by justincjohnson** [labzero/bootleg#162]
I have a Phoenix umbrella project with two apps (myapp and myapp_web).  At the top level of the repo my rel/config.exs looks like the following.

```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"SECRET_COOKIE"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"SECRET_COOKIE"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :myapp do
  set version: "0.1.0"
  set applications: [
    :runtime_tools,
    myapp: :permanent,
    myapp_web: :permanent
  ]
end
```

If I build the release with `mix release` it builds fine and creates `_build/prod/rel/tree/releases/0.1.0/myapp.tar.gz`. If I build using `mix bootleg.build` the same file is created, but I get the following output after the build completes.  Is there some special configuration needed to make this work with umbrella projects?

```
[10.2.0.49 ] ==> Assembling release..
[10.2.0.49 ] ==> Building release myapp:0.1.0 using environment prod
[10.2.0.49 ] ==> One or more direct or transitive dependencies are missing from
[10.2.0.49 ]     :applications or :included_applications, they will not be included
[10.2.0.49 ]     in the release:
[10.2.0.49 ]
[10.2.0.49 ]     :elixir_make
[10.2.0.49 ]
[10.2.0.49 ]     This can cause your application to fail at runtime. If you are sure
[10.2.0.49 ]     that this is not an issue, you may ignore this warning.
[10.2.0.49 ] ==> Including ERTS 9.0 from /usr/lib/erlang/erts-9.0
[10.2.0.49 ] ==> Packaging release..
[10.2.0.49 ] ==> Release successfully built!
[10.2.0.49 ]     You can run it in one of the following ways:
[10.2.0.49 ]       Interactive: _build/prod/rel/myapp/bin/myapp console
[10.2.0.49 ]       Foreground: _build/prod/rel/myapp/bin/myapp foreground
Downloading release archive
[10.2.0.49 ] DOWNLOAD /data/bootleg/build/_build/prod/rel//releases/0.0.1/.tar.gz -> releases/0.0.1.tar.gz
unsupported user key algorithm :"ssh-dss"
CentOS: Access or use of this system is restricted to authorized users only. The following are strictly prohibited: unauthorized disruption of the traceable, correct, and complete functions of this system inclusive of communication, processing and software, destruction, alteration or disclosure of data or cryptographic keys contained. Misuse of this system, software, data, or cryptography is subject to both civil and criminal prosecution.** (RuntimeError) SCP download error: Invalid SCP directive received: scp: /data/bootleg/build/_build/prod/rel/releases/0.0.1/.tar.gz: No such file or directory

 lib/bootleg/ssh.ex:122: Bootleg.SSH.download/3
 lib/strategies/build/distillery.ex:142: Bootleg.Strategies.Build.Distillery.download_release_archive/2
 lib/bootleg/config.ex:311: Bootleg.Config.invoke/1
 deps/bootleg/lib/bootleg/tasks/update.exs:4: Bootleg.DynamicTasks.Update.execute/0
 lib/bootleg/config.ex:311: Bootleg.Config.invoke/1
 (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
 (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```

**Comment by justincjohnson** [comment]
I should note that in the output above the path `/data/bootleg/build/_build/prod/rel//releases/0.0.1/.tar.gz` looks like it is looking at mix.exs at the top level of the umbrella project, which lacks an app name and includes a version of 0.0.1.  These were the defaults for a new Phoenix 1.3 umbrella project.

**Comment by rjanja** [comment]
In your Bootleg config could you try the following and see if it corrects the error:

```elixir
use Bootleg.Config
# ...
config :app, :myapp
```

Thanks!

**Comment by rjanja** [comment]
We're defaulting the app to `Mix.Project.config[:app]` and as you pointed out, umbrella projects don't have this set. I think this can be considered a bug until we have a better solution. Thanks for all the good feedback!

**Comment by justincjohnson** [comment]
If I add both of these lines to config/deploy.exs I get past the error.

```
config :app, :myapp
config :version, "0.1.0"
```

I'll have to think through the significance of the app names and versions in umbrella projects and update config accordingly during releases.  Thanks again.
