### ISSUE TITLE
before_task :compile symlinking secret not allowed

### ISSUE THREAD

**Issue by snewcomer** [labzero/bootleg#198]
So trying to symlink my prod.secret.exs and getting an error [here](https://github.com/labzero/bootleg/blob/3f5cef191372e0bc0e094d3f2a26afbb5a35a669/lib/strategies/build/distillery.ex#L119) before `invoke :compile`, thus not allowing me to symlink/copy with the `before_task :compile` task.  So `mix local.rebar --force` is the specific command looking for the prod.secret.exs file.  I also tried `after_task :clean` as well with no dice.  Eventually I used `replace_os_vars` in the prod secret file and removed from gitignore.  If you think a PR could come out of this, I'd be happy to help.  Otherwise, I can close.

```
** (SSHError) Command exited on 127.0.0.1 with non-zero status (1)
     cmd: MIX_ENV=prod mix local.rebar --force
  stderr: ** (Mix.Config.LoadError) could not load config config/prod.secret.exs
              ** (File.Error) could not read file "/tmp/bootleg/build/config/prod.secret.exs": no such file or directory
              (elixir) lib/file.ex:272: File.read!/1
              (mix) lib/mix/config.ex:180: Mix.Config.read!/2
              (mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
              (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
              (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
              (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
              (stdlib) erl_eval.erl:404: :erl_eval.expr/5

    lib/bootleg/ssh.ex:169: Bootleg.SSH.run_result/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/strategies/build/distillery.ex:24: Bootleg.Strategies.Build.Distillery.build/0
    lib/bootleg/config.ex:356: Bootleg.Config.invoke/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```

**Comment by holetse** [comment]
@snewcomer Thanks for getting in touch. Are you trying to symlink on the remote build server or the local working copy? Can you share your `before_task :compile` hook?

**Comment by snewcomer** [comment]
Trying to symlink on a local build.  

```
before_task :compile do
   System.ln_s!("/home/me/Github/my-project/config/prod.secret.exs", "/tmp/bootleg/build/config/prod.secret.exs")
 end
```

Also tried

```
before_task :compile do
  "cp /home/me/Github/my-project/config/prod.secret.exs /tmp/bootleg/build/config/prod.secret.exs"`
end
```

**Comment by anildigital** [comment]
👍 

```
task :copy_secret_file do
  IO.puts("~~~~ Running this")

  System.cmd("cp", [
    "/Users/anil/Projects/prod_secrets/prod.secret.exs",
    "config/prod.secret.exs"
  ])
end

before_task(:build, :copy_secret_file)
```
Tried using server paths above.. still no luck. Tried other options too such as `before_task(:compile)`

Could you please document steps for how to copy prod.secret.exs? I think there is bug.

**Comment by guidotripaldi** [comment]
I think the problem is within the (currently) lacks of before/after hooks for the tasks where new commits are pushed to the `:build` server.

In fact, if you try to look at the sequence of hooks invocation, you will see that after the end of the `:clean` task a new block of commands starts, where the commands for '_Pushing new commits with git_', '_Resetting remote hosts to refspec_' and '_Fetching / Updating dependencies_' are executed in sequence without any task hooks separation between them. This is the sequence we get (details stripped, full transcript further) doing a `$ mix bootleg.build` command:


```
[myapp_umbrella (master)]$ mix bootleg.build
====> append_revision(0.0.1) = "0.0.1+bdb14ef"

# before_task :build
Creating remote context at 'build/bootleg/build'
[...]

# before_task :clean
Creating remote context at 'build/bootleg/build'
[...]
# after_task :clean

# following operations doesn't seems to belong to a task for that we have a hook to inject our code for manage the secret files:
Pushing new commits with git to: myusername@build.example.com

Resetting remote hosts to refspec "master"
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env git reset --hard master)

Fetching / Updating dependencies
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env MIX_ENV=prod mix local.rebar --force)
** (SSHError) Command exited on build.example.com with non-zero status (1)


```


We will see that we cannot copy/symlink the secret files just after the `:clean` task, because copying/symlinking will act before having the directory structure where to put our files/symlinks (structure that was deleted by the previous `:clean` task, and  that will be (re)built by the successive, but never reatched because of the upload/symlink error, '_Fetching / Updating dependencies_' task):


```
[myapp_umbrella (master)]$ mix bootleg.build
====> append_revision(0.0.1) = "0.0.1+bdb14ef"

# before_task :build
Creating remote context at 'build/bootleg/build'
[...]

# before_task :clean
Creating remote context at 'build/bootleg/build'
[...]
# after_task :clean

# try to upload secret
Creating remote context at 'build/bootleg/build'
[build.example.com] (export REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p build/bootleg/build)
[build.example.com] UPLOAD apps/myapp/config/prod.secret.exs -> build/bootleg/build/apps/myapp/config/prod.secret.exs
** (FunctionClauseError) no function clause matching in SSHKit.SCP.Upload.warning/3

    The following arguments were given to SSHKit.SCP.Upload.warning/3:

        # 1
        [as: "apps/myapp/config/prod.secret.exs", recursive: true]

        # 2
        {:write, "prod.secret.exs", %File.Stat{access: :read_write, atime: 1511346706, ctime: 1510583267, gid: 20, inode: 2255213, links: 1, major_device: 16777220, minor_device: 0, mode: 33188, mtime: 1510583267, size: 369, type: :regular, uid: 502}, "/Users/Me/Development/Elixir/testbootleg/myapp_umbrella/apps/myapp/config", [[]], []}

        # 3
        "scp: build/bootleg/build/apps/myapp/config/prod.secret.exs: No such file or directory\n"
[...]

```



So to be able to put the code for copying/symlinking the `prod.secret.exs` file **we probably need a new, specific start/end hook _between_ the '_Pushing new commits with git_' task and the '_Fetching/Updating dependencies_' task**.


That said, I really love this library: it is really very well structured and documentation is exceptionally clear! :-)




This is the config/deploy.exs file used to produce the below examples for a plain vanilla Phoenix umbrella app:

```
# config/deploy.exs
use Bootleg.Config

role :build, "build.example.com", user: "myusername", password: "mypassword", workspace: "build/bootleg/build"

config(:app, :myapp_umbrella)
config(:version, "0.0.1")




before_task :build do
	IO.puts "\n# before_task :build"
end

before_task :clean do
	IO.puts "\n# before_task :clean"
end

before_task :compile do
	IO.puts "\n# before_task :compile"
end

before_task :generate_release do
	IO.puts "\n# before_task :generate_release"
end

before_task :phoenix_digest do
	IO.puts "\n# before_task :phoenix_digest"
end



after_task :clean do
	IO.puts "# after_task :clean\n"

	IO.puts "#{IO.ANSI.blue}----> try to upload secret"
	upload :build, "apps/myapp/config/prod.secret.exs", "apps/myapp/config/prod.secret.exs"
end

after_task :compile do
	IO.puts "# after_task :compile\n"
end

after_task :generate_release do
	IO.puts "# after_task :generate_release\n"
end


after_task :phoenix_digest do
	IO.puts "# after_task :phoenix_digest\n"
end
```

This is the full transcript of the `$ mix bootleg.build` without trying to copy/symlinking the secret files:

```
[myapp_umbrella (master)]$ mix bootleg.build
====> append_revision(0.0.1) = "0.0.1+bdb14ef"

****> before_task :build
Creating remote context at 'build/bootleg/build'
[build.example.com] (export REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p build/bootleg/build)
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env git init)
[build.example.com] Reinitialized existing Git repository in /home/myusername/build/bootleg/build/.git/
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env git config receive.denyCurrentBranch ignore)

****> before_task :clean
Creating remote context at 'build/bootleg/build'
[build.example.com] (export REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p build/bootleg/build)
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env rm -rvf *)
[build.example.com] removed `README.md'
[build.example.com] removed `apps/myapp_web/config/test.exs'
[build.example.com] removed `apps/myapp_web/config/prod.exs'
[build.example.com] removed `apps/myapp_web/config/config.exs'
[build.example.com] removed `apps/myapp_web/config/dev.exs'

[...]

[build.example.com] removed directory: `config/deploy'
[build.example.com] removed directory: `config'
[build.example.com] removed `mix.exs'
[build.example.com] removed `mix.lock'
[build.example.com] removed `rel/config.exs'
[build.example.com] removed directory: `rel'
****> after_task :clean

Pushing new commits with git to: myusername@build.example.com
[build.example.com] Everything up-to-date
[build.example.com]
Resetting remote hosts to refspec "master"
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env git reset --hard master)
[build.example.com] HEAD is now at bdb14ef Change config
[build.example.com] HEAD is now at bdb14ef Change config
[build.example.com]
Skipped cleaning generated files from last build
Fetching / Updating dependencies
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env MIX_ENV=prod mix local.rebar --force)
** (SSHError) Command exited on build.example.com with non-zero status (1)
     cmd: MIX_ENV=prod mix local.rebar --force
  stderr: warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
  stderr: ** (Mix.Config.LoadError) could not load config apps/myapp/config/prod.secret.exs
              ** (File.Error) could not read file "/home/myusername/build/bootleg/build/apps/myapp/config/prod.secret.exs": no such file or directory
              (elixir) lib/file.ex:244: File.read!/1
              (mix) lib/mix/config.ex:180: Mix.Config.read!/2
              (mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
              (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
              (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
              (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
              (stdlib) erl_eval.erl:404: :erl_eval.expr/5

    lib/bootleg/ssh.ex:169: Bootleg.SSH.run_result/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/strategies/build/distillery.ex:24: Bootleg.Strategies.Build.Distillery.build/0
    lib/bootleg/config.ex:356: Bootleg.Config.invoke/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
[myapp_umbrella (master)]$
```

This is the full transcript of the `$ mix bootleg.build` trying to copy/symlinking the secret files:

```
[myapp_umbrella (master)]$ mix bootleg.build
====> append_revision(0.0.1) = "0.0.1+bdb14ef"

****> before_task :build
Creating remote context at 'build/bootleg/build'
[build.example.com] (export REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p build/bootleg/build)
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env git init)
[build.example.com] Reinitialized existing Git repository in /home/myusername/build/bootleg/build/.git/
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env git config receive.denyCurrentBranch ignore)

****> before_task :clean
Creating remote context at 'build/bootleg/build'
[build.example.com] (export REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p build/bootleg/build)
[build.example.com] cd build/bootleg/build && (export REPLACE_OS_VARS="true" && /usr/bin/env rm -rvf *)
****> after_task :clean

----> try to upload secret
Creating remote context at 'build/bootleg/build'
[build.example.com] (export REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p build/bootleg/build)
[build.example.com] UPLOAD apps/myapp/config/prod.secret.exs -> build/bootleg/build/apps/myapp/config/prod.secret.exs
** (FunctionClauseError) no function clause matching in SSHKit.SCP.Upload.warning/3

    The following arguments were given to SSHKit.SCP.Upload.warning/3:

        # 1
        [as: "apps/myapp/config/prod.secret.exs", recursive: true]

        # 2
        {:write, "prod.secret.exs", %File.Stat{access: :read_write, atime: 1511346706, ctime: 1510583267, gid: 20, inode: 2255213, links: 1, major_device: 16777220, minor_device: 0, mode: 33188, mtime: 1510583267, size: 369, type: :regular, uid: 502}, "/Users/Me/Development/Elixir/testbootleg/myapp_umbrella/apps/myapp/config", [[]], []}

        # 3
        "scp: build/bootleg/build/apps/myapp/config/prod.secret.exs: No such file or directory\n"

    Attempted function clauses (showing 1 out of 1):

        defp warning(_, {name, cwd, stack, errs} = state, buffer)

    lib/sshkit/scp/upload.ex:151: SSHKit.SCP.Upload.warning/3
    lib/sshkit/ssh/channel.ex:224: SSHKit.SSH.Channel.loop/4
    lib/sshkit/ssh.ex:125: SSHKit.SSH.run/3
    lib/sshkit/ssh.ex:68: SSHKit.SSH.connect/3
    lib/sshkit.ex:353: anonymous fn/4 in SSHKit.upload/3
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:183: Bootleg.SSH.upload/3
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
[myapp_umbrella (master)]$
```

**Comment by snewcomer** [comment]
I think you are correct!  So in my case, when `invoke :compile` is instantiated, the correct `before_hooks` are called.  However, `cmd: MIX_ENV=prod mix local.rebar --force` requires a `prod.secret.exs` file.

So if this block of [code](https://github.com/labzero/bootleg/blob/3f5cef191372e0bc0e094d3f2a26afbb5a35a669/lib/strategies/build/distillery.ex#L119) could be put in the `compile` task, everything would be a ok.

**Comment by jherdman** [comment]
Was this ever really resolved? I'm finding it challenging to symlink my prod secrets like this:

```elixir
before_task :compile do
  remote do
    "mkdir -p /tmp/bootleg/build/config && ln -nfs $HOME/prod.secret.exs config/prod.secret.exs"
  end
end
```

**Comment by acezone** [comment]
@jherdman I figured this out tonight. If you upgrade to the master branch via git in mix.exs then you can use the new hooks that have been defined. I was able to get past this point using

```
before_task :compile do
  IO.puts("Copy Secret")

  remote :build do
    "cp /my/dir/prod.secret.exs /tmp/bootleg/config"
  end
end
```
