### ISSUE TITLE
ssh_client_key_api compilation error

### ISSUE THREAD

**Issue by abarr** [labzero/bootleg#247]
I tried to implement Bootleg to build and deploy a Phoenix application to an Ubuntu server from my Macbook. 

My config/deploy.exs:

```
use Bootleg.Config

role :build, "server.com", user: "dev", identity: "/Users/me/.ssh/dev_phoenix_build", workspace: "/tmp/bootleg/build"
```

My config/deploy/production.exs:

```
use Bootleg.Config

role :app, "server.com", user: "dev", identity: "/Users/me/.ssh/dev_phoenix_build", workspace: "/var/www/server.com/html"
```

I have also added` :phoenix_bootleg` to my deps.

On the Ubunto server it gets to the ssh_client_key_api and fails with the following message:

```
stdout: ==> ssh_client_key_api
  stdout: Compiling 1 file (.ex)
  stdout:
          == Compilation error in file lib/ssh_client_key_api.ex ==
          ** (UndefinedFunctionError) function :ssh.default_algorithms/0 is undefined (module :ssh is not available)
              :ssh.default_algorithms()
              lib/ssh_client_key_api.ex:4: (module)
              (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
  stderr: could not compile dependency :ssh_client_key_api, "mix compile" failed. You can recompile this dependencywith "mix deps.compile ssh_client_key_api", update it with "mix deps.update ssh_client_key_api" or clean it with "mix deps.clean ssh_client_key_api"

    lib/bootleg/ssh.ex:169: Bootleg.SSH.run_result/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    deps/bootleg/lib/bootleg/tasks/build.exs:46: anonymous fn/4 in Bootleg.DynamicTasks.Compile.execute/0
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/bootleg/config.ex:356: Bootleg.Config.invoke/1
    deps/bootleg/lib/bootleg/tasks/build.exs:19: Bootleg.DynamicTasks.Build.execute/0
    lib/bootleg/config.ex:356: Bootleg.Config.invoke/1

```
I have not been able to work out what is going on yet. Any assistance will be greatly appreciated.

Thanks in advance

**Comment by brienw** [comment]
Hi @abarr, just checking in to see if you are still seeing this issue? My initial thought is that you might be missing the `:ssh` OTP library since one of the errors is:
`(module :ssh is not available)`
On ubuntu, I think you may need to additionally install the `erlang-ssh` package.

sorry for the super late response
