### ISSUE TITLE
Can't connect to the build server (SSHKit returned an internal error)

### ISSUE THREAD

**Issue by matixmatix** [labzero/bootleg#315]
`mix bootleg.build` fails when trying to connect to my server.

My `deploy.exs`config is:

```
use Bootleg.DSL

role :build, "107.170.130.xx",
  workspace: "/home/deploy/apps/myapp/",
  user: "deploy",
  identity: "~/.ssh/id_rsa",
  silently_accept_hosts: true
```

This is the output I get:

````
[21:25:19] jurgen:myapp git:(master*) $ mix bootleg.build
Starting remote build for production environment
[107.170.130.44] (export BOOTLEG_ENV="production" REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p /home/deploy/apps/gitfuck/)

21:29:08.773 [info]  Erlang SSH :client 4.8 (OpenSSL 1.1.1d  10 Sep 2019).
Server: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.13'
Disconnects with code = 14 [RFC4253 11.1]: Unable to connect using the available authentication methods
State = {userauth,client}
Module = ssh_connection_handler, Line = 904.
Details:
  User auth failed for: "deploy"


** (SSHError) SSHKit returned an internal error on 107.170.130.44: 'Unable to connect using the available authentication methods'
    lib/bootleg/ssh.ex:99: anonymous fn/2 in Bootleg.SSH.run/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:118: Bootleg.SSH.run!/2
    lib/bootleg/ssh.ex:141: Bootleg.SSH.validate_workspace/3
    lib/bootleg/ssh.ex:58: Bootleg.SSH.init/2
    deps/bootleg/lib/bootleg/tasks/build/remote.exs:36: anonymous fn/2 in Bootleg.DynamicTasks.Init.execute/0
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/bootleg/dsl.ex:370: Bootleg.DSL.invoke/1
````

What could be the problem? I believe I have a standard key generated with `ssh-keygen`. I also tried generating another key with `ssh-keygen -t rsa -b 4096` and tried using it as `identity` but got the same issue.

When I try connecting manually with ssh: `ssh deploy@107.170.130.xx`, everything works fine.

Any ideas?

**Environment:**
- Bootleg version: 0.12.0
- Elixir version: 1.9.1
- Erlang/OTP version: 22

**Comment by matixmatix** [comment]
I figured it out.

The key #1 didn't work because it has a passphrase.

The key #2 didn't work because I'm an idiot (forgot to put it in the authorized_keys in the server).

Now it works using the newly generated key that doesn't have a passphrase.
